# -------------------------------------------------------------------------------------------------
# Config file to the display
# Author: Valdigleis (valdigleis@gmail.com)
# -------------------------------------------------------------------------------------------------

# Transparency
background_opacity 0.85

# Padding used
window_padding_width 4

# Disable bell alert
enable_audio_bell no
window_alert_on_bell yes

# Visual bell alert icon
bell_on_tab "🔔 "

# Enable progress bar
progress_bar top

# Define window layout
remember_window_size  yes
initial_window_width  320
initial_window_height 200
remember_window_position yes

# Tab bar configs
tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_switch_strategy previous
tab_bar_align left
tab_fade 0.25 0.5 0.75 1
tab_bar_style fade
