# -------------------------------------------------------------------------------------------------
# Config file to the display
# Author: Valdigleis (valdigleis@gmail.com)
# -------------------------------------------------------------------------------------------------

# Transparency
background_opacity 0.85

# Padding used
window_padding_width 4

# Disable bell alert
enable_audio_bell no
window_alert_on_bell yes

# Visual bell alert icon
bell_on_tab "🔔 "

# Enable progress bar
progress_bar top

# Define window layout
remember_window_size  no
initial_window_width  800
initial_window_height 400
remember_window_position yes

# Tab bar configs
tab_bar_edge top
tab_bar_style custom
tab_bar_margin_height 0.0 0.0
tab_title_template "{title}"
tab_bar_min_tabs 1
