# -------------------------------------------------------------------------------------------------
# Config file to fonts
# Author: Valdigleis (valdigleis@gmail.com)
# -------------------------------------------------------------------------------------------------

# Fonte
font_family      Hack Nerd Font

# Tamanho da Fonte
font_size 15
